// <auto-generated />
using System;
using EstoqueApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstoqueApp.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstoqueApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("EstoqueApp.Models.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CostCenter", (string)null);
                });

            modelBuilder.Entity("EstoqueApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("CurrentStock");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<decimal>("MinStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("MinStock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("SKU");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitOfMeasureId");

                    b.HasIndex(new[] { "Name" }, "IX_ProductName")
                        .IsUnique();

                    b.HasIndex(new[] { "Sku" }, "IX_Product_Sku")
                        .IsUnique();

                    b.ToTable("Product", null, t =>
                        {
                            t.HasCheckConstraint("CK_Product_CurrentStock_NonNegative", "[CurrentStock] >= 0");

                            t.HasCheckConstraint("CK_Product_UnitPrice_NonNegative", "[UnitPrice]   >= 0");
                        });
                });

            modelBuilder.Entity("EstoqueApp.Models.StockByCostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdate")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("ProductId", "CostCenterId")
                        .IsUnique();

                    b.ToTable("StockByCostCenter", (string)null);
                });

            modelBuilder.Entity("EstoqueApp.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Description");

                    b.Property<int?>("DestinationCostCenterId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginCostCenterId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Quantity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex(new[] { "Date" }, "IX_StockMovement_Date");

                    b.HasIndex(new[] { "DestinationCostCenterId" }, "IX_StockMovement_DestinationCC");

                    b.HasIndex(new[] { "OriginCostCenterId" }, "IX_StockMovement_OriginCC");

                    b.HasIndex(new[] { "ProductId" }, "IX_StockMovement_Product");

                    b.ToTable("StockMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockMovement_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_StockMovement_Type_Allowed", "[Type] IN ('Entry','Exit','Transfer')");
                        });
                });

            modelBuilder.Entity("EstoqueApp.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Abbreviation" }, "IX_UnitOfMeasure_Abbreviation")
                        .IsUnique();

                    b.ToTable("UnitOfMeasure", (string)null);
                });

            modelBuilder.Entity("EstoqueApp.Models.Product", b =>
                {
                    b.HasOne("EstoqueApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("EstoqueApp.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Product_UnitOfMeasure");

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("EstoqueApp.Models.StockByCostCenter", b =>
                {
                    b.HasOne("EstoqueApp.Models.CostCenter", "CostCenter")
                        .WithMany("StocksByCostCenter")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StockByCC_CostCenter");

                    b.HasOne("EstoqueApp.Models.Product", "Product")
                        .WithMany("StocksByCostCenter")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StockByCC_Product");

                    b.Navigation("CostCenter");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EstoqueApp.Models.StockMovement", b =>
                {
                    b.HasOne("EstoqueApp.Models.CostCenter", null)
                        .WithMany("Movements")
                        .HasForeignKey("CostCenterId");

                    b.HasOne("EstoqueApp.Models.CostCenter", "DestinationCostCenter")
                        .WithMany()
                        .HasForeignKey("DestinationCostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Movement_DestinationCostCenter");

                    b.HasOne("EstoqueApp.Models.CostCenter", "OriginCostCenter")
                        .WithMany()
                        .HasForeignKey("OriginCostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Movement_OriginCostCenter");

                    b.HasOne("EstoqueApp.Models.Product", "Product")
                        .WithMany("Movements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Movement_Product");

                    b.Navigation("DestinationCostCenter");

                    b.Navigation("OriginCostCenter");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EstoqueApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EstoqueApp.Models.CostCenter", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("StocksByCostCenter");
                });

            modelBuilder.Entity("EstoqueApp.Models.Product", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("StocksByCostCenter");
                });

            modelBuilder.Entity("EstoqueApp.Models.UnitOfMeasure", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
